[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.24"  # Match GroveACLOracle.sol pragma
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[profile.zksync]
src = 'src'
libs = ['lib']
solc-version = "0.8.24"
fallback_oz = true
is_system = false
mode = "3"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]